-- ============================================================================
-- dw LAYER: STAR SCHEMA - DDL
-- Viagens de Carro da Uber e Ola
-- ============================================================================

DROP SCHEMA IF EXISTS dw CASCADE;
CREATE SCHEMA dw;

COMMENT ON SCHEMA dw IS 'Camada dw - Dados agregados e otimizados para análise';

-- ============================================================================
-- DIMENSÕES
-- ============================================================================

-- ----------------------------------------------------------------------------
-- DIM_ROT: Dimensão de Rota (Pickup + Drop Location)
-- ----------------------------------------------------------------------------
CREATE TABLE dw.dim_rot (
    rot_key BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pck_loc VARCHAR(255) NOT NULL,
    drp_loc VARCHAR(255) NOT NULL,
    
    -- Constraint de unicidade
    CONSTRAINT uk_dim_rot_loc UNIQUE (pck_loc, drp_loc)
);

COMMENT ON TABLE dw.dim_rot IS 'Dimensão de rotas - combinação de origem e destino';
COMMENT ON COLUMN dw.dim_rot.rot_key IS 'Chave SRK - gerada automaticamente';
COMMENT ON COLUMN dw.dim_rot.pck_loc IS 'Local de embarque (pickup location)';
COMMENT ON COLUMN dw.dim_rot.drp_loc IS 'Local de destino (drop location)';

-- Índices DIM_ROT
CREATE INDEX idx_dim_rot_loc ON dw.dim_rot(pck_loc, drp_loc);

-- ----------------------------------------------------------------------------
-- DIM_CST: Dimensão de Cliente
-- ----------------------------------------------------------------------------
CREATE TABLE dw.dim_cst (
    cst_key BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cst_idf VARCHAR(50) NOT NULL,
    cst_rtg NUMERIC(3,2),
    
    -- Constraint de unicidade
    CONSTRAINT uk_dim_cst_idf UNIQUE (cst_idf)
);

COMMENT ON TABLE dw.dim_cst IS 'Dimensão de clientes';
COMMENT ON COLUMN dw.dim_cst.cst_key IS 'Chave SRK - gerada automaticamente';
COMMENT ON COLUMN dw.dim_cst.cst_idf IS 'Identificador anonimizado do cliente';
COMMENT ON COLUMN dw.dim_cst.cst_rtg IS 'Avaliação média histórica do cliente';

-- Índices DIM_CST
CREATE INDEX idx_dim_cst_idf ON dw.dim_cst(cst_idf);

-- ----------------------------------------------------------------------------
-- DIM_STS: Dimensão de Status da Viagem
-- ----------------------------------------------------------------------------
CREATE TABLE dw.dim_sts (
    sts_key BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bkg_sts VARCHAR(100) NOT NULL,
    cld_cst TEXT,
    cld_drv TEXT,
    icm_rid BOOLEAN DEFAULT FALSE,
    icm_rid_rsn TEXT,
    
    -- Constraint de unicidade
    CONSTRAINT uk_dim_sts_sts UNIQUE (bkg_sts, cld_cst, cld_drv, icm_rid, icm_rid_rsn)
);

COMMENT ON TABLE dw.dim_sts IS 'Dimensão de status da viagem e motivos de cancelamento';
COMMENT ON COLUMN dw.dim_sts.sts_key IS 'Chave SRK - gerada automaticamente';
COMMENT ON COLUMN dw.dim_sts.bkg_sts IS 'Status final da reserva (Success, Canceled by Driver, Canceled by Customer)';
COMMENT ON COLUMN dw.dim_sts.cld_cst IS 'Motivo do cancelamento informado pelo cliente';
COMMENT ON COLUMN dw.dim_sts.cld_drv IS 'Motivo do cancelamento informado pelo motorista';
COMMENT ON COLUMN dw.dim_sts.icm_rid IS 'Indica se a viagem foi iniciada mas não concluída';
COMMENT ON COLUMN dw.dim_sts.icm_rid_rsn IS 'Motivo da não conclusão da viagem';

-- Índices DIM_STS
CREATE INDEX idx_dim_sts_sts ON dw.dim_sts(bkg_sts);

-- ----------------------------------------------------------------------------
-- DIM_TIM: Dimensão Temporal
-- ----------------------------------------------------------------------------
CREATE TABLE dw.dim_tim (
    tim_key BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dat DATE NOT NULL,
    tim TIME NOT NULL,
    
    -- Constraint de unicidade
    CONSTRAINT uk_dim_tim_dat UNIQUE (dat, tim)
);

COMMENT ON TABLE dw.dim_tim IS 'Dimensão temporal com data e hora';
COMMENT ON COLUMN dw.dim_tim.tim_key IS 'Chave SRK - gerada automaticamente';
COMMENT ON COLUMN dw.dim_tim.dat IS 'Data da solicitação da viagem';
COMMENT ON COLUMN dw.dim_tim.tim IS 'Hora da solicitação da viagem';

-- Índices DIM_TIM
CREATE INDEX idx_dim_tim_dat ON dw.dim_tim(dat, tim);

-- ----------------------------------------------------------------------------
-- DIM_PAY: Dimensão de Método de Pagamento
-- ----------------------------------------------------------------------------
CREATE TABLE dw.dim_pay (
    pay_key BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pay_mtd VARCHAR(50),
    
    -- Constraint de unicidade
    CONSTRAINT uk_dim_pay_mtd UNIQUE (pay_mtd)
);

COMMENT ON TABLE dw.dim_pay IS 'Dimensão de métodos de pagamento';
COMMENT ON COLUMN dw.dim_pay.pay_key IS 'Chave SRK - gerada automaticamente';
COMMENT ON COLUMN dw.dim_pay.pay_mtd IS 'Forma de pagamento utilizada (Cash, UPI, Credit Card, etc.)';

-- Índices DIM_PAY
CREATE INDEX idx_dim_pay_mtd ON dw.dim_pay(pay_mtd);

-- ----------------------------------------------------------------------------
-- DIM_VEC: Dimensão de Tipo de Veículo
-- ----------------------------------------------------------------------------
CREATE TABLE dw.dim_vec (
    vec_key BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vec_typ VARCHAR(50) NOT NULL,
    
    -- Constraint de unicidade
    CONSTRAINT uk_dim_vec_typ UNIQUE (vec_typ)
);

COMMENT ON TABLE dw.dim_vec IS 'Dimensão de tipos de veículo';
COMMENT ON COLUMN dw.dim_vec.vec_key IS 'Chave SRK - gerada automaticamente';
COMMENT ON COLUMN dw.dim_vec.vec_typ IS 'Categoria do veículo solicitado (Prime Sedan, Bike, Auto, etc.)';

-- Índices DIM_VEC
CREATE INDEX idx_dim_vec_typ ON dw.dim_vec(vec_typ);

-- ============================================================================
-- TABELA FATO
-- ============================================================================

-- ----------------------------------------------------------------------------
-- CAR_TRP: Tabela Fato de Viagens
-- ----------------------------------------------------------------------------
CREATE TABLE dw.car_trp (
    trp_key BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    
    -- Chaves Estrangeiras (Dimensões)
    sts_srk BIGINT,
    tim_srk BIGINT,
    cst_srk BIGINT,
    pay_srk BIGINT,
    vec_srk BIGINT,
    rot_srk BIGINT,
    
    -- Métricas/Fatos
    rid_dst INTEGER,
    drv_rtg NUMERIC(3,2),
    bkg_val NUMERIC(10,2),
    drv_tim_acp INTEGER,
    psg_tim_bdg INTEGER,
    
    -- Foreign Keys
    CONSTRAINT fk_car_trp_sts FOREIGN KEY (sts_srk) REFERENCES dw.dim_sts(sts_key),
    CONSTRAINT fk_car_trp_tim FOREIGN KEY (tim_srk) REFERENCES dw.dim_tim(tim_key),
    CONSTRAINT fk_car_trp_cst FOREIGN KEY (cst_srk) REFERENCES dw.dim_cst(cst_key),
    CONSTRAINT fk_car_trp_pay FOREIGN KEY (pay_srk) REFERENCES dw.dim_pay(pay_key),
    CONSTRAINT fk_car_trp_vec FOREIGN KEY (vec_srk) REFERENCES dw.dim_vec(vec_key),
    CONSTRAINT fk_car_trp_rot FOREIGN KEY (rot_srk) REFERENCES dw.dim_rot(rot_key)
);

COMMENT ON TABLE dw.car_trp IS 'Tabela fato de viagens - centro do modelo star schema com 6 dimensões';
COMMENT ON COLUMN dw.car_trp.trp_key IS 'Chave SRK - gerada automaticamente';
COMMENT ON COLUMN dw.car_trp.sts_srk IS 'Chave estrangeira para dimensão de status';
COMMENT ON COLUMN dw.car_trp.tim_srk IS 'Chave estrangeira para dimensão temporal';
COMMENT ON COLUMN dw.car_trp.cst_srk IS 'Chave estrangeira para dimensão de cliente';
COMMENT ON COLUMN dw.car_trp.pay_srk IS 'Chave estrangeira para dimensão de pagamento (nullable)';
COMMENT ON COLUMN dw.car_trp.vec_srk IS 'Chave estrangeira para dimensão de veículo';
COMMENT ON COLUMN dw.car_trp.rot_srk IS 'Chave estrangeira para dimensão de rota';
COMMENT ON COLUMN dw.car_trp.rid_dst IS 'Distância estimada da viagem';
COMMENT ON COLUMN dw.car_trp.drv_rtg IS 'Avaliação média histórica do motorista';
COMMENT ON COLUMN dw.car_trp.bkg_val IS 'Valor cobrado pela viagem';
COMMENT ON COLUMN dw.car_trp.drv_tim_acp IS 'Tempo (em segundos) até o motorista aceitar a corrida';
COMMENT ON COLUMN dw.car_trp.psg_tim_bdg IS 'Tempo (em segundos) até o embarque do passageiro';

-- Índices CAR_TRP (Tabela Fato)
-- Índices nas chaves estrangeiras (para joins com dimensões)
CREATE INDEX idx_car_trp_sts_srk ON dw.car_trp(sts_srk);
CREATE INDEX idx_car_trp_tim_srk ON dw.car_trp(tim_srk);
CREATE INDEX idx_car_trp_cst_srk ON dw.car_trp(cst_srk);
CREATE INDEX idx_car_trp_pay_srk ON dw.car_trp(pay_srk);
CREATE INDEX idx_car_trp_vec_srk ON dw.car_trp(vec_srk);
CREATE INDEX idx_car_trp_rot_srk ON dw.car_trp(rot_srk);

-- Índices compostos para queries analíticas comuns
CREATE INDEX idx_car_trp_tim_sts ON dw.car_trp(tim_srk, sts_srk);
CREATE INDEX idx_car_trp_vec_sts ON dw.car_trp(vec_srk, sts_srk);

-- ============================================================================
-- FIM DO DDL
-- ============================================================================